## Installing NumPy library

In [ ]:
pip install Numpy

In [ ]:
import numpy as np

## Printing np version
print(np.__version__)

2.4.1


## Creating NumPy Arrays

We create 3 different types of NumPy arrays: a 1D array, a 2D array, and a 3D array.


In [8]:
onedarray = np.array(np.arange(1,11))
onedarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
twodaarray = np.array(np.arange(1,10)).reshape(3,3)
twodaarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
fromList = np.array([10,20,30,40,50])
fromList

array([10, 20, 30, 40, 50])

## Mathematical Operations on NumPy Arrays

We are going to perform some basic mathematical operations on NumPy arrays such as addition, subtraction, multiplication, and division.

In [15]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

def addition(A, B):
    return A + B

def subtraction(A, B):
    return A - B

def multiplication(A, B):
    return A * B

def division(A, B):
    return A / B

print("Addition:\n", addition(A, B))
print("Subtraction:\n", subtraction(A, B))
print("Multiplication:\n", multiplication(A, B))
print("Division:\n", division(A, B))

## Implementing the same using inbuilt numpy functions
print("Addition using np.add:\n", np.add(A, B))
print("Subtraction using np.subtract:\n", np.subtract(A, B))
print("Multiplication using np.multiply:\n", np.multiply(A, B))
print("Division using np.divide:\n", np.divide(A, B))

Addition:
 [11 22 33 44]
Subtraction:
 [ 9 18 27 36]
Multiplication:
 [ 10  40  90 160]
Division:
 [10. 10. 10. 10.]
Addition using np.add:
 [11 22 33 44]
Subtraction using np.subtract:
 [ 9 18 27 36]
Multiplication using np.multiply:
 [ 10  40  90 160]
Division using np.divide:
 [10. 10. 10. 10.]


## Important Numpy Mathematical Functions

With Numpy functions we are going to calculate Square root, Exponential, Logarithm, Sum and Cumulative sum of elements in an array.

In [16]:
values = np.array([2,4,6,8,10])
print("Square root of each element: \n", np.sqrt(values))
print("Exponential of each element: \n", np.exp(values))
print("Log of each value: \n", np.log(values))
print("Sum of each values: \n", np.sum(values))
print("Cumulative sum of each values: \n", np.cumulative_sum(values))

Square root of each element: 
 [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential of each element: 
 [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Log of each value: 
 [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum of each values: 
 30
Cumulative sum of each values: 
 [ 2  6 12 20 30]


## Aggregation Operations

We are going to find Row wise sum, Column wise sum, Minimum value, Maximum value, Overall mean of a 2 Dimensional matrix

In [ ]:
data = np.array(np.arange(10, 100, 10)).reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
## Column-wise sum
print("Column wise sum: \n", np.sum(data, axis=0))

# Row-wise sum
print("Row wise sum: \n", np.sum(data, axis=1))

Column wise sum: 
 [120 150 180]
Row wise sum: 
 [ 60 150 240]


In [22]:
## Finding Minimum and maximum value
print("Minimum value: \n", np.min(data))
print("Maximum value: \n", np.max(data))

Minimum value: 
 10
Maximum value: 
 90


In [23]:
## Finding mean
print("Mean of values: \n", np.mean(data))

Mean of values: 
 50.0


## Statistical operations in Numpy

Now we are going to apply the Statistical operations on a 1-D array. This is the core focus of Numpy library

In [26]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
print("Mean: \n", np.mean(marks))
print("Median: \n", np.median(marks))
print("Variance: \n", np.var(marks))
print("Standard Deviation: \n", np.std(marks))
print(f"Minimum mark: \n{np.min(marks)} Maximum mark: \n{np.max(marks)}")
print("Marks in range 80 - 90: \n", marks[np.where((marks >= 80) & (marks <= 90))])

Mean: 
 79.25
Median: 
 81.5
Variance: 
 134.1875
Standard Deviation: 
 11.583932838203095
Minimum mark: 
60 Maximum mark: 
95
Marks in range 80 - 90: 
 [85 90 88]


## Percentiles and sorting in Numpy

With the same marks array we are going to find 25th, 50th and 75th percentiles and also sort the array in ascending order

In [32]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
print("25th Percentile: \n", np.percentile(marks, 25))
print("50th Percentile: \n", np.percentile(marks, 50))
print("75th Percentile: \n", np.percentile(marks, 75))
print("Sorted marks in ascending order: \n", np.sort(marks))
print("Average of marks: \n", np.mean(marks))
print(f"Number of students who scored more than {np.mean(marks)}: \n", np.sum(marks > np.mean(marks)))

25th Percentile: 
 70.5
50th Percentile: 
 81.5
75th Percentile: 
 88.5
Sorted marks in ascending order: 
 [60 66 72 78 85 88 90 95]
Average of marks: 
 79.25
Number of students who scored more than 79.25: 
 4


## Mini use case : Sales data analysis

In [34]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
print("Total sales: ", np.sum(sales))
print("Average sales: ", np.mean(sales).round(2))
print("Highest sales: ", np.max(sales))
print("Lowest sales: ", np.min(sales))
print("Standard deviation of sales: ", np.std(sales).round(2))
print(f"Number of days with sales above average ({np.mean(sales).round(2)}): ", np.sum(sales > np.mean(sales).round(2)))

Total sales:  10700
Average sales:  1528.57
Highest sales:  2000
Lowest sales:  900
Standard deviation of sales:  345.23
Number of days with sales above average (1528.57):  4
